FROM node:20-alpine AS app

WORKDIR /app

COPY package*.json ./
COPY apps ./apps

RUN npm ci
RUN npm run prisma:generate --workspace=@bosque/api
RUN npm run build --workspace=@bosque/api

COPY deploy/entrypoint-api.sh /entrypoint-api.sh
RUN chmod +x /entrypoint-api.sh

ENV NODE_ENV=production
EXPOSE 3000

CMD ["/entrypoint-api.sh"]
