FROM node:20-alpine AS app

WORKDIR /app

COPY package*.json ./
COPY apps ./apps

RUN npm ci
RUN npm run prisma:generate --workspace=@bosque/api
RUN npm run build --workspace=@bosque/api

ENV NODE_ENV=production
EXPOSE 3000

CMD ["sh", "-c", "npm exec --workspace=@bosque/api prisma migrate deploy --schema apps/api/prisma/schema.prisma && npm run start:prod --workspace=@bosque/api"]
