# ========== PROD BOSQUE MAGICO (HTTP + ACME) ==========
server {
    listen 80;
    server_name bosquemagico.gcbprojects.site admin.bosquemagico.gcbprojects.site;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
